### ISSUE TITLE
dateutil modulen kom inte med i v0.5 

### ISSUE THREAD

**Issue by Sire** [bitsofwinter/cryptotaxsweden#14]
Windows v0.5 fungerar inte alls. Verkar som pyinstaller missade att ta med dateutil:

> report.exe
```
Traceback (most recent call last):
  File "report.py", line 6, in <module>
  File "c:\temp\build_cts\repo\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "taxdata.py", line 2, in <module>
ModuleNotFoundError: No module named 'dateutil'
[11148] Failed to execute script report
```

**Comment by OriginalMadman** [comment]
same prob, broken

**Comment by bitsofwinter** [comment]
Hopefully 0.6 will work better.
