### ISSUE TITLE
Get error message:  Traceback (most recent call last):   File "report.py", line 38, in <module>   File "taxdata.py", line 98, in read_from IndexError: list index out of range [20976] Failed to execute script report

### ISSUE THREAD

**Issue by Instantexit** [bitsofwinter/cryptotaxsweden#18]
When i use the windows executable, and input my trades.csv from cointracking, trying to generate a simplified report.

I get these error messages: 

C:\cryptotaxsweden>report 2018 --simplified-k4
Traceback (most recent call last):
  File "report.py", line 38, in <module>
  File "taxdata.py", line 98, in read_from
IndexError: list index out of range
[20976] Failed to execute script report

What could be the problem here, any ideas how to solve it?

Thanks!

**Comment by Instantexit** [comment]
Nevermind, Silly me, I missed you were supposed to export csv from Trade prices and not where you enter coins. Now i just need to fix a few negative coins where they got delisted and I have a hard time finding out when I actually bought them anymore because markets are gone on exchange....sigh... Thanks for this nice program, I appreciate it alot!
