### ISSUE TITLE
error message: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 35: invalid start byte [11640] Failed to execute script report

### ISSUE THREAD

**Issue by Instantexit** [bitsofwinter/cryptotaxsweden#20]
I now get this error message: 
C:\cryptotaxsweden>report 2018 --simplified-k4 
Traceback (most recent call last):
  File "report.py", line 39, in <module>
  File "taxdata.py", line 83, in read_from
  File "taxdata.py", line 83, in <listcomp>
  File "c:\temp\build_cts\repo\venv\lib\codecs.py", line 321, in decode
  File "c:\temp\build_cts\repo\venv\lib\encodings\utf_8_sig.py", line 69, in _buffer_decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 35: invalid start byte
[11640] Failed to execute script report

Any ideas what is causing this error?

**Comment by Instantexit** [comment]
I googled this problem, but its way over my computer ability to comprehend/fix. Will try to run the script on my other machine and see what happens then. Does anyone else get this error?

**Comment by bitsofwinter** [comment]
Have you edited the trades.csv file manually or is it downloaded straight from cointracking? If you are editing any files, then make sure to save in UTF-8, you can do this with a text editor such as Notepad++.
